---
title: 前端代码输出题-重复出错  
date: 2022-07-23 19:55:34  
permalink: /pages/EOEKDME/  
categories:
    - 前端
    - 前端基础概念
tags:
    - 基础
    - 面试
author:  
    name: WJYGRIT   
    link: https://github.com/GRITWJY  
---

# 前端代码输出题-重复出错

## 1
```javascript
var myObject = {
    foo: "bar",
    func: function() {
        var self = this;
        console.log(this.foo);   
        console.log(self.foo);   
        (function() {
            console.log(this.foo);   
            console.log(self.foo);   
        }());
    }
};
myObject.func();
```

:::details 解析
- 1.第一个this.foo输出bar，因为当前this指向对象myObject。
- 2.第二个self.foo输出bar，因为self是this的副本，同指向myObject对象。
- 3.第三个this.foo输出undefined，因为这个IIFE(立即执行函数表达式)中的this指向window。
- 4.第四个self.foo输出bar，因为这个匿名函数所处的上下文中没有self，所以通过作用域链向上查找，从包含它的父函数中找到了指向myObject对象的self。
:::


## 2
```javascript
var a = 1;
function fn(){
    var a = 2;
    function a(){console.log(3);}
    return a;
    function a(){console.log(4);}
}
var b = fn();
console.log(b);
```
:::details 解析
输出的b值为函数fn内的变量a，在函数fn内部，由于存在变量提升和函数提升，且函数提升会在变量提升之前，因此变量a会先被赋值为函数f a(){console.log(3);}，之后被重新赋值为函数f a(){console.log(4);}，最后被赋值为2，所以b值为2.
:::


## 3
```javascript
var obj = {brand:'华为',price:1999};
Object.defineProperty(obj,'id',{value:1})
Object.defineProperty(obj,'price',{configurable:false})
console.log(Object.keys(obj).length);// ① 2
for (var k in obj){
    console.log(obj[k]); //② 华为  1999
}
obj.price = 999;
delete obj['price']
console.log(obj);// ③ {brand:'华为', price:999,id:1}
```

:::details 解析
- Object.keys(obj) 返回obj对象中自身可枚举属性组成的数组, 虽然obj对象新增了id属性, 但该属性是不可枚举的, 故1式的结果是2
- 使用for...in...循环可以遍历对象可枚举的属性，id属性由于不可枚举，因此仍然不会被遍历到，②式的输出结果为华为 1999
- rice属性设置了configurable:false，表示该属性不可删除，删改无效，也不可再次修改其特性，但是属性值是可以重写的
:::


## 4.


```javascript
const promise = new Promise((resolve,reject)=>{
    console.log(1);
    resolve();
    console.log(2);
    reject()
})
setTimeout(()=>{console.log(5)},0)
promise.then(()=>{console.log(3)})
.then(()=>{console.log(6)})
.catch(()=>{console.log(7)})
console.log(4)
```

:::details 解析
答案是1,2,4,3,6,5

首先new Promise时候打印1和2，因为new Promise时候会立即执行传入的方法

然后后面代码都是异步代码，先将setTimeout的回调加入宏任务队列，再把promise.then放入到微任务队列，然后直接执行最后一句，打印4

这样宏任务代码执行完了，接下来开始执行微任务队列中的任务，由于promise resolve，因为promise resolve之后状态不会再改变，因此不会执行到reject的对调，所以打印3和6

微任务队列为空，再到宏任务队列中查找任务，找到setTimeout回调执行，打印5

调用栈、宏任务队列、微任务队列都为空，代码执行结束。
:::


## 5
```javascript
const first = () => (new Promise((resolve, reject) => {
    console.log(3);
    let p = new Promise((resolve, reject) => {
        console.log(7);
        setTimeout(() => {
            console.log(5);
            resolve();
        }, 0);
        resolve(1);
    });
    resolve(2);
    p.then((arg) => {
        console.log(arg);
    });
}));
first().then((arg) => {
    console.log(arg);
});
console.log(4);
```

:::details 解析
3, 7, 4, 1, 2, 5

首先定义first

然后执行first，然后执行new Promise传入的方法，先打印3

又new Promise，执行其中传入的方法，打印7

执行setTimeout，将回调放入宏任务队列

执行resolve(1)，将内部promise状态置为fullfilled，值为1

执行resolve(2)，将外部promise状态置为fullfilled，值为2

执行内部promise.then方法，将回调加入微任务队列

执行first().then，即外部的promise，将回调加入到微任务队列

调用栈为空，开始从微任务队列拿取任务，首先拿到内部promise的回调，打印其值1

然后从微任务队列中拿取外部的promise的回调，打印其值2

此时微任务队列为空，开始从宏任务队列中拿取任务，即setTimeout回调，打印5。

调用栈，宏任务队列和微任务队列都为空，执行结束。
:::




## 6.

```javascript
const p1 = new Promise((resolve) => {
  setTimeout(() => {
    resolve('resolve3');
    console.log('timer1')
  }, 0)
  resolve('resovle1');
  resolve('resolve2');
}).then(res => {
  console.log(res)
  setTimeout(() => {
    console.log(p1)
  }, 1000)
}).finally(res => {
  console.log('finally', res)
})

```
:::details
- Promise的状态一旦改变就无法改变
- finally不管Promise的状态是resolved还是rejected都会执行，且它的回调函数是接收不到Promise的结果的，所以finally()中的res是一个迷惑项。
- 最后一个定时器打印出的p1其实是`.finally`的返回值，我们知道`.finally`的返回值如果在没有抛出错误的情况下默认会是上一个Promise的返回值，而这道题中`.finally`上一个Promise是 `.then()`，但是这个`.then()`并没有返回值，所以p1打印出来的Promise的值会是undefined，如果你在定时器的下面加上一个return 1，则值就会变成1
:::



## 7.
```javascript
const async1 = async () => {
  console.log('async1');
  setTimeout(() => {
    console.log('timer1')
  }, 2000)
  await new Promise(resolve => {
    console.log('promise1')
  })
  console.log('async1 end')
  return 'async1 success'
} 
console.log('script start');
async1().then(res => console.log(res));
console.log('script end');
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .catch(4)
  .then(res => console.log(res))
setTimeout(() => {
  console.log('timer2')
}, 1000)

```

:::details
- async函数中await的new Promise要是没有返回值的话则不执行后面的内容
- `.the`n函数中的参数期待的是函数，如果不是函数的话会发生透传
- 注意定时器的延迟时间
:::




## 8.
```javascript
async function async1 () {
  try {
    await Promise.reject('error!!!')
  } catch(e) {
    console.log(e)
  }
  console.log('async1');
  return Promise.resolve('async1 success')
}
async1().then(res => console.log(res))
console.log('script start')

```
