---
title: vue错误处理
date: 2022-05-27 15:25:34
permalink: /pages/nbtm92aq/
categories:
    - 前端
    - 前端技巧
tags:
    - JS
author:
    name: WJYGRIT
    link: https://github.com/GRITWJY
---

# vue错误处理机制

[原文地址](https://mp.weixin.qq.com/s/V0s-EFFjBAYqqOedIEWqdw)

## 1、 vue错误处理
### errorHandler

- err 可获取错误信息、堆栈信息
- vm 可获取报错的vm实例（也就是对应的组件）
- info 可获取特定错误信息。如生命周期信息 created hook，事件信息 v-on handler

```javascript
// main.js
Vue.config.errorHandler = function (err, vm, info) {
  console.log('全局捕获 err >>>', err)
  console.log('全局捕获 vm >>>', vm)
  console.log('全局捕获 info >>>', info)
}
```


### errorCaptured
这里是组件的一个错误处理机制，相当于生命周期。只能捕获子组件的错误。

而且，如果return false 的话，全局errorHandler 就不会收到错误，不然会执行两遍
```
errorCaptured(err, vm, info) {
  // 添加errorCaptured钩子，其余跟上述案例一致
  console.log('父组件捕获 err >>>', err, vm, info)
}
```


## vue错误捕获机制
<img :src="$withBase('/nbtm92aq/img.png')" alt="foo"/>

## 源码分析
代码位于 `src/core/util/error.js`。共四个方法: `handleError、invokeWithErrorHandling、globalHandleError，logError`


### 1、 handlerError
Vue 中的错误统一处理函数，在此函数中实现向上通知 `errorCaptured` 直到全局 `errorHandler` 的功能。核心解读如下：

- 参数 err、vm、info
- pushTarget、popTarget。源码中注释有写到，主要是避免处理错误时 组件 无限渲染
- $parent。Vue 组件树中建立父子关系的属性，可以通过该属性不断向上查找顶层组件——大Vue(也就是我们初始化时候new Vue的那个)，大Vue的 $parent 是 undefined
- 获取errorCaptured。可能有小伙伴有疑问这里为什么是个数组，因为 Vue 初始化的时候会对 hook 做合并处理。比如说我们用到 mixins 的时候，组件中可能会出现多个相同的 hook，初始化时会把这些 cb 都合并在一个 hook 的数组里，以便触发钩子的时候一一调用
- capture。如果为false的时候，直接 return，不会走到 globalHandleError 中

```javascript
// 很明显，这个参数的就是我们熟悉的 err、vm、info
function handleError (err: Error, vm: any, info: string) {
  pushTarget()
  try {
    if (vm) {
      let cur = vm
      // 向上查找$parent，直到不存在
      // 注意了！一上来 cur 就赋值给 cur.$parent，所以 errorCaptured 不会在当前组件的错误捕获中执行
      while ((cur = cur.$parent)) {
        // 获取钩子errorCaptured
        const hooks = cur.$options.errorCaptured
        if (hooks) {
          for (let i = 0; i < hooks.length; i++) {
            try {
              // 执行errorCaptured
              const capture = hooks[i].call(cur, err, vm, info) === false
              // errorCaptured返回false，直接return，外层的globalHandleError不会执行
              if (capture) return
            } catch (e) {
              // 如果在执行errorCaptured的时候捕获到错误，会执行globalHandleError，此时的info为：errorCaptured hook
              globalHandleError(e, cur, 'errorCaptured hook')
            }
          }
        }
      }
    }
    // 外层，全局捕获，只要上面不return掉，就会执行
    globalHandleError(err, vm, info)
  } finally {
    popTarget()
  }
}
```


### 2. invokeWithErrorHandling

一个包装函数，内部使用try-catch 包裹传入的函数，且有更好的处理异步错误的能力。可处理 生命周期 、 事件 等回调函数的错误捕获。可处理返回值是Promise的异步错误捕获。捕获到错误后，统一派发给 handleError ，由它处理向上通知到全局的逻辑。核心解读如下：

- 参数 handler 。传入的执行函数，在内部对其调用，并对其返回值进行Promise的判断
- try-catch。使用 try-catch 包裹并执行传入的函数，捕获错误后调用 handleError 。（是不是有点高阶函数那味呢～）
- handleError。捕获错误后也是调用 handleError 方法对错误进行向上通知
```javascript
function invokeWithErrorHandling (
  handler: Function,
  context: any,
  args: null | any[],
  vm: any,
  info: string
) {
  let res
  try {
    // 处理handle的参数并调用
    res = args ? handler.apply(context, args) : handler.call(context)
    // 判断返回是否为Promise 且 未被catch(!res._handled)
    if (res && !res._isVue && isPromise(res) && !res._handled) {
      res.catch(e => handleError(e, vm, info + ` (Promise/async)`))
      // _handled标志置为true，避免嵌套调用时多次触发catch
      res._handled = true
    }
  } catch (e) {
    // 捕获错误后调用 handleError
    handleError(e, vm, info)
  }
  return res
}
```

### 3. globalHandleError

全局错误捕获。也就是我们在全局配置的 Vue.config.errorHandler的触发函数

- 内部用 try-catch 包裹 errorHandler 的执行。在这里就会执行我们全局的错误捕获函数～
- 如果执行 errorHandler 中存在错误则被捕获后通过 logError 打印。（logError 在浏览器的生产环境的使用 console.error 打印）
- 如果没有 errorHandler。则会直接使用 logError 进行错误打印

```javascript
function globalHandleError (err, vm, info) {
  if (config.errorHandler) {
    try {
      // 调用全局的 errorHandler 并return
      return config.errorHandler.call(null, err, vm, info)
    } catch (e) {
      // 翻译源码注释：如果用户故意在处理程序中抛出原始错误，不要记录两次      
      if (e !== err) {
        // 对在 globalHandleError 中的错误进行捕获，通过 logError 输出
        logError(e, null, 'config.errorHandler')
      }
    }
  }
  // 如果没有 errorHandler 全局捕获，则执行到这里，用 logError 错误
  logError(err, vm, info)
}
```


### 4. logError

实现对错误信息的打印（开发环境、线上会有所不同）

- warn。开发环境中会使用 warn 打印错误。以 [Vue warn]: 开头
- console.error。浏览器环境中使用 console.error 对捕获的错误进行输出
```javascript
// logError源码实现
function logError (err, vm, info) {
  if (process.env.NODE_ENV !== 'production') {
    // 开发环境中使用 warn 对错误进行输出
    warn(`Error in ${info}: "${err.toString()}"`, vm)
  }
  /* istanbul ignore else */
  if ((inBrowser || inWeex) && typeof console !== 'undefined') {
    // 直接用 console.error 打印错误信息
    console.error(err)
  } else {
    throw err
  }
}

// 简单看看 warn 的实现
warn = (msg, vm) => {
  const trace = vm ? generateComponentTrace(vm) : ''
  if (config.warnHandler) {
    config.warnHandler.call(null, msg, vm, trace)
  } else if (hasConsole && (!config.silent)) {
    // 这就是我们平时常见的 Vue warn 打印报错的由来了！
    console.error(`[Vue warn]: ${msg}${trace}`)
  }
}
```


### 简单总结一下：

- handleError：统一的错误捕获函数。实现子组件到顶层组件错误捕获后对 errorCaptured hook 的冒泡调用，执行完全部的 errorCaptured 钩子后最终执行全局错误捕获函数 globalHandleError。
- invokeWithErrorHandling：包装函数，通过高阶函数的编程私思路，通过接收一个函数参数，并在内部使用 try-catch 包裹后执行传入的函数；还提供更好的异步错误处理，当执行函数返回了一个Promise对象，会在此对其实现进行错误捕获，最后也是通知到 handleError 中（如果我们未自己对返回的Promise进行catch操作）
- globalHandleError：调用全局配置的 errorHandler 函数，如果在调用的过程中捕获到错误，则通过 logError 打印所捕获的错误，以 'config.errorHandler' 结尾
- logError。实现对未捕获的错误信息进行打印输出。开发环境会打印2种错误信息～

